apiVersion: v1
kind: Pod
metadata:
  name: graceful-shutdown
spec:
  containers:
    - name: graceful-shutdown
      image: node:erbium
      command:
        - node
        - /app/index.js
      env:
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-auth
              key: token
      volumeMounts:
        - name: script-file
          mountPath: /app
  volumes:
    - name: script-file
      configMap:
        name: script-file
  restartPolicy: Never
