apiVersion: v1
kind: Pod
metadata:
  name: pod-delete
spec:
  containers:
    - name: pod-delete
      image: walk8243/kubernetes-pod-delete:latest
      env:
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-auth
              key: token
      lifecycle:
        preStop:
          exec:
            command:
              - node
              - --icu-data-dir=/app/node_modules/full-icu
              - /app/preStop.js
  terminationGracePeriodSeconds: 15
  restartPolicy: Never
